graph [ 
  comment "Binary tree"
  node [ id 1 label "Node 1" ]
  node [ id 2 label "Node 2" ]
  node [ id 3 label "Node 3" ]
  node [ id 4 label "Node 4" ]
  node [ id 5 label "Node 5" ]
  node [ id 6 label "Node 6" ]
  node [ id 7 label "Node 7" ]
  node [ id 8 label "Node 8" ]
  node [ id 9 label "Node 9" ]
  node [ id 10 label "Node 10" ]
  node [ id 11 label "Node 11" ]
  node [ id 12 label "Node 12" ]
  node [ id 13 label "Node 13" ]
  node [ id 14 label "Node 14" ]
  node [ id 15 label "Node 15" ]
  node [ id 16 label "Node 16" ]
  node [ id 17 label "Node 17" ]
  node [ id 18 label "Node 18" ]
  node [ id 19 label "Node 19" ]
  node [ id 20 label "Node 20" ]
  node [ id 21 label "Node 21" ]
  node [ id 22 label "Node 22" ]
  node [ id 23 label "Node 23" ]
  node [ id 24 label "Node 24" ]
  node [ id 25 label "Node 25" ]
  node [ id 26 label "Node 26" ]
  node [ id 27 label "Node 27" ]
  node [ id 28 label "Node 28" ]
  node [ id 29 label "Node 29" ]

  edge [ source 1 target 2 ]
  edge [ source 1 target 3 ]
  edge [ source 2 target 4 ]
  edge [ source 2 target 5 ]
  edge [ source 3 target 6 ]
  edge [ source 3 target 7 ]
  edge [ source 4 target 8 ]
  edge [ source 4 target 9 ]
  edge [ source 5 target 10 ]
  edge [ source 5 target 11 ]
  edge [ source 6 target 12 ]
  edge [ source 6 target 13 ]
  edge [ source 7 target 14 ]
  edge [ source 7 target 15 ]
  edge [ source 8 target 16 ]
  edge [ source 8 target 17 ]
  edge [ source 9 target 18 ]
  edge [ source 9 target 19 ]
  edge [ source 9 target 20 ]
  edge [ source 9 target 21 ]
  edge [ source 9 target 22 ]
  edge [ source 9 target 23 ]
  edge [ source 9 target 24 ]
  edge [ source 9 target 25 ]
  edge [ source 9 target 26 ]
  edge [ source 10 target 27 ]
  edge [ source 10 target 28 ]
  edge [ source 10 target 29 ]
]

